name: Release app

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [default, prometheus]
    steps:
      - uses: actions/checkout@v4

      - name: Install latest stable x86_64-unknown-linux-gnu toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: vkgates
          features: ${{ matrix.features }}
          archive: $bin-${{ matrix.features }}-$tag-$target
          asset: README.md,LICENSE,.env_variable
          token: ${{ secrets.GITHUB_TOKEN }}
